import{i as l,S as f}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function e(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=e(r);fetch(r.href,t)}})();const g="https://pixabay.com/api/",m="46110623-cffeede45492ee1adb33fe3c4";function d(s){const o=new URLSearchParams({key:m,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${g}?${o}`).then(e=>{if(!e.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return e.json()}).catch(e=>{throw new Error("An error occurred while fetching images. Please try again later.")})}function h(s){return s.reduce((o,e)=>o+`<article class="gallery-item">
                <a href="${e.largeImageURL}" class="gallery-link">
                    <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
                </a>
                <ul class="info">
                    <li class="info-item"><strong>Likes:</strong> ${e.likes}</li>
                    <li class="info-item"><strong>Views:</strong> ${e.views}</li>
                    <li class="info-item"><strong>Comments:</strong> ${e.comments}</li>
                    <li class="info-item"><strong>Downloads:</strong> ${e.downloads}</li>
                </ul>
            </article>`,"")}const y=document.querySelector(".search-form"),c=document.querySelector(".gallery"),u=document.querySelector(".loader");let i=null;function p(){u.style.display="block"}function w(){u.style.display="none"}y.addEventListener("submit",s=>{s.preventDefault();const o=s.target.elements.query.value.trim();if(!o){l.warning({title:"Warning",message:"Please enter a search query."});return}p(),c.innerHTML="",d(o).then(e=>{const{hits:n}=e;if(n.length===0)throw new Error("No images found for this search query.");const r=h(n);c.innerHTML=r,i?i.refresh():i=new f(".gallery a",{captions:!0,captionDelay:250})}).catch(e=>{l.error({title:"Error",message:e.message})}).finally(()=>{w()})});
//# sourceMappingURL=index.js.map
